### ISSUE TITLE
Parsing ipp-bistro fails

### ISSUE THREAD

**Issue by COM8** [srehwald/eat-api#15]
If I try to parse the dishes for the IPP, it fails:

`$ python3 main.py ipp-bistro`

```
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 76, in main
    menus = parser.parse(location)
  File "/home/fabian/eat-api/menu_parser.py", line 287, in parse
    call(["pdftotext", "-l", "1", "-layout", temp_pdf.name, temp_txt.name])
  File "/usr/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pdftotext'
```

It seems like it misses the `pdftotext` file.

**Comment by srehwald** [comment]
Yes, this file is missing and there is a good reason for that. `pdftotext` is a little tool which is part of `poppler-utils` that converts pdf to text. Obviously, you need to install `poppler-utils` first. In my `.travis.yml`, it is also installed before the script is executed.

Does this explain the failure?

**Comment by COM8** [comment]
Yes, great, thanks :smile: !
