### ISSUE TITLE
Parsing fmi-bistro fails 

### ISSUE THREAD

**Issue by COM8** [srehwald/eat-api#16]
If I try to parse the dishes for the FMI, it fails:
`$  python3 main.py fmi-bistro`

```
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main()
  File "main.py", line 58, in main
    menus = parser.parse(location)
  File "/home/fabian/test/eat-api/src/menu_parser.py", line 173, in parse
    week_number = int(pdf_name.split("_")[2].replace("KW","").lstrip("0"))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by srehwald** [comment]
I love it if they change their naming scheme week by week ...
Fixed it; will be part of the next release.
